version: "3.7"

services:
  swimmy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swimmy
    restart: unless-stopped
    environment:
      SLACK_BOT_USERNAME: ${SLACK_BOT_USERNAME}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_BOT_SIGNING_SECRET: ${SLACK_BOT_SIGNING_SECRET}
      SWIMLANE_HOST: ${SWIMLANE_HOST}
      SWIMLANE_USERNAME: ${SWIMLANE_USERNAME}
      SWIMLANE_PASSWORD: ${SWIMLANE_PASSWORD}
      #SWIMLANE_ACCESS_TOKEN: ${SWIMLANE_ACCESS_TOKEN}
      SWIMLANE_VERIFY_SSL: ${SWIMLANE_VERIFY_SSL}
      #SWIMLANE_VERIFY_SERVER_VERSION: ${SWIMLANE_VERIFY_SERVER_VERSION}
      #SWIMLANE_DEFAULT_TIMEOUT: ${SWIMLANE_DEFAULT_TIMEOUT}
      #SWIMLANE_RESOURCE_CACHE_SIZE: ${SWIMLANE_RESOURCE_CACHE_SIZE}
      #SWIMLANE_WRITE_TO_READ_OLNLY: ${SWIMLANE_WRITE_TO_READ_OLNLY}
      SWIMLANE_SEARCH_RESULTS_MAX_RESULTS: ${SWIMLANE_SEARCH_RESULTS_MAX_RESULTS}
    ports:
     - "3000:3000"
    volumes: ['./swimmy:/swimmy']
